return table.freeze({
	SchemaVersion = 1,
	DataStoreName = "FootballTransferHeist_v1",
	MaxPlayers = 2,
	MaxActivePlayers = 6,
	AutosaveSeconds = 60,
	TransferWindowSeconds = 300,
	ContractsPerWindow = 3,
	ContractPickupDistance = 14,
	ContractDropCooldown = 1.25,
	DepositRadius = 22,
	SafeZoneRadius = 38,
	SlideTackleRange = 9,
	SlideTackleCooldown = 4,
	SlideKnockback = 44,
	GuardianHitRadius = 5.5,
	GuardianTickSeconds = 0.1,
	EconomyTickSeconds = 1,
	TrainingTickSeconds = 0.5,
})
