return table.freeze({
	SchemaVersion = 2,
	DataStoreName = "FootballTransferRivals_v2",
	MaxPlayers = 6,
	AutosaveSeconds = 60,
	TransferWindowSeconds = 300,
	ContractsPerZone = 3,
	ContractPickupDistance = 14,
	ContractDropCooldown = 1.25,
	DroppedReturnSeconds = 20,
	DepositRadius = 28,
	SlideTackleRange = 10,
	SlideTackleCooldown = 4,
	SlideKnockback = 44,
	GuardianHitRadius = 5.5,
	GuardianTickSeconds = 0.1,
	EconomyTickSeconds = 1,
	TrainingTickSeconds = 0.25,
	StartingSlots = 6,
	MaximumSlots = 20,
})
